/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package management;

import DSA.Employee;
import DSA.EmployeeDSA;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giang
 */
public class frmEmployee extends javax.swing.JFrame {

    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    EmployeeDSA dsEm = new EmployeeDSA();

    public frmEmployee() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrGen = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLPEmployee = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbEmployee = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jTFLastName = new javax.swing.JTextField();
        jTFFirstName = new javax.swing.JTextField();
        jTFDateofBirth = new javax.swing.JTextField();
        jRBtMale = new javax.swing.JRadioButton();
        jRBtFemale = new javax.swing.JRadioButton();
        jTFPosition = new javax.swing.JTextField();
        jTFPhoneNum = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jBtReset = new javax.swing.JButton();
        jBtAdd = new javax.swing.JButton();
        jBtUpdate = new javax.swing.JButton();
        jBtDel = new javax.swing.JButton();
        jBtSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        jLPEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTbEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ", "Tên", "Ngày sinh", "Giới tính", "Vị trí", "Số điện thoại", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbEmployee);

        jLabel7.setText("Mã nhân viên");

        jLabel8.setText("Họ ");

        jLabel9.setText("Tên");

        jLabel10.setText("Ngày sinh");

        jLabel11.setText("Giới tính");

        jLabel12.setText("Vị trí");

        jLabel13.setText("Địa chỉ");

        jLabel14.setText("Số điện thoại");

        jTFDateofBirth.setText("dd/mm/yyyy");

        btGrGen.add(jRBtMale);
        jRBtMale.setSelected(true);
        jRBtMale.setText("Nam");

        btGrGen.add(jRBtFemale);
        jRBtFemale.setText("Nữ");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane3.setViewportView(address);

        jBtReset.setText("Làm mới");
        jBtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtResetActionPerformed(evt);
            }
        });

        jBtAdd.setText("Thêm");
        jBtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddActionPerformed(evt);
            }
        });

        jBtUpdate.setText("Sửa");
        jBtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtUpdateActionPerformed(evt);
            }
        });

        jBtDel.setText("Xóa");
        jBtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDelActionPerformed(evt);
            }
        });

        jBtSearch.setText("Tìm kiếm");
        jBtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSearchActionPerformed(evt);
            }
        });

        jLPEmployee.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFDateofBirth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jRBtMale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jRBtFemale, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFPosition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jTFPhoneNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jBtReset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jBtAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jBtUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jBtDel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLPEmployee.setLayer(jBtSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLPEmployeeLayout = new javax.swing.GroupLayout(jLPEmployee);
        jLPEmployee.setLayout(jLPEmployeeLayout);
        jLPEmployeeLayout.setHorizontalGroup(
            jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBtMale, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRBtFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPEmployeeLayout.createSequentialGroup()
                        .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPEmployeeLayout.createSequentialGroup()
                        .addComponent(jBtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLPEmployeeLayout.createSequentialGroup()
                        .addComponent(jBtSearch)
                        .addGap(74, 74, 74)
                        .addComponent(jBtReset))
                    .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTFPhoneNum)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(jTFPosition)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
        );
        jLPEmployeeLayout.setVerticalGroup(
            jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLPEmployeeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(jTFLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLPEmployeeLayout.createSequentialGroup()
                        .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jTFFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jRBtMale)
                            .addComponent(jRBtFemale)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtReset)
                        .addComponent(jBtSearch))
                    .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtUpdate)
                        .addComponent(jBtDel)
                        .addComponent(jBtAdd)))
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(jLPEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLPEmployeeLayout.createSequentialGroup()
                    .addGap(0, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPEmployee)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPEmployee)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTb() {
        DefaultTableModel tb = (DefaultTableModel) jTbEmployee.getModel();
        tb.setRowCount(0);
        for (int i = 0; i < dsEm.eList.size(); i++) {
            Object[] row = new Object[8];
            row[0] = dsEm.eList.get(i).getId();
            row[1] = dsEm.eList.get(i).getLastName();
            row[2] = dsEm.eList.get(i).getFirstName();
            row[3] = dateFormat.format(dsEm.eList.get(i).getDateOfBirth());
            String gen = "Nữ";
            if(dsEm.eList.get(i).getGen())
                gen = "Nam";
            row[4] = gen;
            row[5] = dsEm.eList.get(i).getPosition();
            row[6] = dsEm.eList.get(i).getPhoneNum();
            row[7] = dsEm.eList.get(i).getAddress();
            tb.addRow(row);
        }
    }
    
    public void resetForm() {
        jTFId.setText("");
        jTFFirstName.setText("");
        jTFLastName.setText("");
        jTFDateofBirth.setText("");
        jRBtMale.setSelected(true);
        jTFPosition.setText("");
        jTFPhoneNum.setText("");
        address.setText("");
    }

    public Employee getModel() throws ParseException {
        Employee e = new Employee();
        e.setId(jTFId.getText());
        e.setLastName(jTFLastName.getText());
        e.setFirstName(jTFFirstName.getText());
        e.setDateOfBirth(dateFormat.parse(jTFDateofBirth.getText()));
        boolean gen = false;
        if(jRBtMale.isSelected()) 
            gen = true;
        e.setGen(gen);
        e.setPosition(jTFPosition.getText());
        e.setPhoneNum(jTFPhoneNum.getText());
        e.setAddress(address.getText());
        return e;
    }

    public void setModel(Employee e) {
        jTFId.setText(e.getId());
        jTFFirstName.setText(e.getFirstName());
        jTFLastName.setText(e.getLastName());
        jTFDateofBirth.setText(dateFormat.format(e.getDateOfBirth()));
        jRBtMale.setSelected(e.getGen());
        jRBtFemale.setSelected(!e.getGen());
        jTFPosition.setText(e.getPosition());
        jTFPhoneNum.setText(e.getPhoneNum());
        address.setText(e.getAddress());
    }

    public boolean checkValidForm() {
        if (jTFId.getText().equals("") || jTFLastName.getText().equals("")
                || jTFFirstName.getText().equals("")
                || jTFDateofBirth.getText().equals("")
                || jTFPhoneNum.getText().equals("")) {
            return false;
        } else if(checkText.checkNum(jTFFirstName.getText()) || 
                checkText.checkCharacter(jTFFirstName.getText()) ||
                checkText.checkNum(jTFLastName.getText()) || 
                checkText.checkCharacter(jTFLastName.getText()) ||
                checkText.checkAllNum(jTFPhoneNum.getText()))
            return false;
        return true;
    }

    private void jBtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddActionPerformed
        if (checkValidForm()) {
            Employee e;
            try {
                e = getModel();
                if (dsEm.add(e) > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Lưu thành công");
                    showTb();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lưu không thành công");
                }
            } catch (ParseException ex) {
                Logger.getLogger(frmEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đầy đủ thông tin hoặc chưa nhập đúng định dạng");
        }
    }//GEN-LAST:event_jBtAddActionPerformed

    private void jBtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtResetActionPerformed
        resetForm();
    }//GEN-LAST:event_jBtResetActionPerformed

    private void jBtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtUpdateActionPerformed
        if (!checkValidForm()) {
            JOptionPane.showMessageDialog(rootPane, "Nhập thông tin để cập nhật");
        } else {
            try {
                Employee e = getModel();
                if (dsEm.update(e) > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                    showTb();
                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Không thể cập nhật nhân viên");
                }
            } catch (ParseException ex) {
                Logger.getLogger(frmEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtUpdateActionPerformed

    private void jBtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDelActionPerformed
        if (jTFId.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập mã nhân viên để xóa");
        } else if (dsEm.del(jTFId.getText()) > 0) {
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
            showTb();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy nhân viên để xóa");
        }
    }//GEN-LAST:event_jBtDelActionPerformed

    private void jBtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSearchActionPerformed
        if (jTFId.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập mã nhân viên để tìm");
        } else {
            Employee e = dsEm.findByID(jTFId.getText());
            if (e != null) {
                setModel(e);
                showTb();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy nhân viên có mã "
                        + jTFId.getText());
            }
        }
    }//GEN-LAST:event_jBtSearchActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup btGrGen;
    private javax.swing.JButton jBtAdd;
    private javax.swing.JButton jBtDel;
    private javax.swing.JButton jBtReset;
    private javax.swing.JButton jBtSearch;
    private javax.swing.JButton jBtUpdate;
    private javax.swing.JLayeredPane jLPEmployee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBtFemale;
    private javax.swing.JRadioButton jRBtMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFDateofBirth;
    private javax.swing.JTextField jTFFirstName;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFLastName;
    private javax.swing.JTextField jTFPhoneNum;
    private javax.swing.JTextField jTFPosition;
    private javax.swing.JTable jTbEmployee;
    // End of variables declaration//GEN-END:variables
}
